const UPDATE_USER_INST = 'UPDATE_USER_INST'
const INSERT_OBJECT = 'INSERT_OBJECT'
const EDIT_OBJECT = 'EDIT_OBJECT'
const DELETE_OBJECT = 'DELETE_OBJECT'

module.exports = {
    UPDATE_USER_INST,
    INSERT_OBJECT,
    EDIT_OBJECT,
    DELETE_OBJECT,
}
