const UPDATE_USER_INST = 'UPDATE_USER_INST'
const UPDATE_WALL = 'UPDATE_WALL'
const COUNT_UP = 'COUNT_UP'
const COUNT_DOWN = 'COUNT_DOWN'
const INSERT_OBJECT = 'INSERT_OBJECT'
const EDIT_OBJECT = 'EDIT_OBJECT'
const DELETE_OBJECT = 'DELETE_OBJECT'

module.exports = {
    UPDATE_USER_INST,
    UPDATE_WALL,
    COUNT_UP,
    COUNT_DOWN,
    INSERT_OBJECT,
    EDIT_OBJECT,
    DELETE_OBJECT,
}
