const UPDATE_USER_INST = 'UPDATE_USER_INST'
const ALTER_LOGIN_NAME = 'ALTER_LOGIN_NAME'
const INSERT_OBJECT = 'INSERT_OBJECT'
const EDIT_OBJECT = 'EDIT_OBJECT'
const DELETE_OBJECT = 'DELETE_OBJECT'
const SWAP_WALL_VIEW = 'SWAP_WALL_VIEW'

module.exports = {
    UPDATE_USER_INST,
    ALTER_LOGIN_NAME,
    INSERT_OBJECT,
    EDIT_OBJECT,
    DELETE_OBJECT,
    SWAP_WALL_VIEW,
}
